# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.20'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
#    tasks: 'build'

- script: sudo apt install -y libxss1 libasound2  # Install required libraries for Playwright
  displayName: 'Install Dependencies'

- script: npx playwright install-deps  # Install Playwright dependencies
  displayName: 'Install Playwright Dependencies'

- script: ./gradlew build  # Build the project
  displayName: 'Build Project'

- script: ./gradlew runHeadlessTest  # Run the Playwright test in headless mode
  displayName: 'Run Playwright Test in Headless Mode'